env_settings:
  env_args: null
  base_port: 5005
  num_envs: 1
  seed: -1
  max_lifetime_restarts: 10
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60

# engine_settings:
#   no_graphics: true
#   width: 84
#   height: 84
#   quality_level: 5
#   time_scale: 20
#   target_frame_rate: -1
#   capture_frame_rate: 60

checkpoint_settings:
  run_id: Test
  initialize_from: null
  load_model: false
  resume: false
  force: true
  train_model: false
  inference: false

torch_settings:
  device: cuda

behaviors:
  Parkour Behavior:
    trainer_type: sac
    max_steps: 1000000
    time_horizon: 128
    summary_freq: 10000

    hyperparameters:
      batch_size: 512
      buffer_size: 50000
      learning_rate: 1.0e-5
      learning_rate_schedule: constant

      buffer_init_steps: 1000
      tau: 0.005
      steps_per_update: 20
      save_replay_buffer: true
      init_entcoef: 0.5
      reward_signal_steps_per_update: 10.0

    network_settings:
      vis_encode_type: simple
      normalize: true
      hidden_units: 512
      num_layers: 3
      memory:
        sequence_length: 64
        memory_size: 256

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0